import type { CaseStudy, Listing } from '@/types/db';

/**
 * Content shown when Supabase is not connected, so a clean clone demonstrates
 * the design instead of rendering empty states everywhere. The UI labels this
 * as demo data wherever it appears.
 *
 * Deliberately absent: demo reviews. An invented testimonial is the one piece
 * of placeholder content that would actually mislead a visitor, so the reviews
 * section stays genuinely empty until a real completed order produces one.
 */

const now = new Date().toISOString();

export const demoCaseStudies: CaseStudy[] = [
  {
    id: 'demo-case-1',
    slug: 'nargiz-dental',
    title: { az: 'Nargiz Dental', en: 'Nargiz Dental', ru: 'Nargiz Dental' },
    client: 'Nargiz Dental, Bakı',
    summary: {
      az: 'Instaqram profilindən onlayn qeydiyyatı olan sayta keçid.',
      en: 'From an Instagram profile to a site that books its own appointments.',
      ru: 'От профиля в Instagram к сайту, который сам записывает пациентов.',
    },
    problem: {
      az: 'Klinikanın bütün qeydiyyatı Instagram mesajları ilə gedirdi. Administrator gündə təxminən qırx mesaja cavab verirdi və axşamlar gələn müraciətlərin bir hissəsi səhərə qədər cavabsız qalırdı. Pasiyentlər qiymətləri soruşmaq üçün də yazmalı olurdu, çünki heç bir yerdə yazılmamışdı.',
      en: 'Every appointment came through Instagram messages. The front desk answered about forty a day, and anything that arrived after hours sat unread until morning. Patients had to message just to ask prices, because the prices were not written down anywhere public.',
      ru: 'Вся запись шла через сообщения в Instagram. Администратор отвечал примерно на сорок сообщений в день, а всё, что приходило вечером, оставалось без ответа до утра. Цены тоже приходилось спрашивать в переписке — нигде опубликованы они не были.',
    },
    built: {
      az: 'Üç dilli sayt, xidmət və qiymət cədvəli, həkimlərin səhifələri və klinikanın öz təqvimi ilə işləyən qeydiyyat forması. Qeydiyyat administratorun telefonuna WhatsApp bildirişi kimi gəlir, ona görə yeni panel öyrənmək lazım olmadı.',
      en: 'A three-language site with a real price list, pages for each dentist, and a booking form wired to the clinic’s own calendar. Bookings arrive as a WhatsApp message on the front-desk phone, so nobody had to learn a new dashboard.',
      ru: 'Трёхъязычный сайт с настоящим прайс-листом, страницами врачей и формой записи, связанной с календарём клиники. Заявка приходит на телефон администратора в WhatsApp — осваивать новую панель никому не пришлось.',
    },
    outcome: {
      az: 'Qeydiyyatların böyük hissəsi indi saytdan gəlir və gecə saatlarında da qeydiyyat açılır. Qiymət soruşan mesajların sayı kəskin azalıb.',
      en: 'Most bookings now come through the site, including overnight ones that used to be lost. The volume of “how much is it?” messages dropped sharply.',
      ru: 'Большая часть записей теперь идёт через сайт, включая ночные, которые раньше терялись. Сообщений «сколько стоит?» стало заметно меньше.',
    },
    industry: 'health',
    stack: ['React', 'Supabase', 'WhatsApp API'],
    tags: ['booking', 'multilingual'],
    year: 2025,
    live_url: null,
    cover_image: '/assets/images/portfolio/nargiz-dental-cover.jpg',
    gallery: [],
    published: true,
    sort_order: 40,
    created_at: now,
  },
  {
    id: 'demo-case-2',
    slug: 'kaspi-yuk',
    title: { az: 'Kaspi Yük', en: 'Kaspi Yük', ru: 'Kaspi Yük' },
    client: 'Kaspi Yük MMC',
    summary: {
      az: 'Yük daşıma şirkəti üçün hesablama forması olan sayt.',
      en: 'A freight company site that answers the price question before the call.',
      ru: 'Сайт транспортной компании, который отвечает на вопрос о цене до звонка.',
    },
    problem: {
      az: 'Şirkətə gələn zənglərin çoxu “Bakıdan Gəncəyə bir ton neçəyə düşür?” sualı idi. Hər zəng operatorun on dəqiqəsini alırdı, müştərilərin isə yarısı qiyməti eşidəndən sonra artıq danışmırdı.',
      en: 'Most incoming calls were a single question: what does a tonne from Baku to Ganja cost? Each one took ten minutes of an operator’s time, and half the callers hung up as soon as they heard the number.',
      ru: 'Большинство звонков сводилось к одному вопросу: сколько стоит тонна из Баку в Гянджу? Каждый звонок отнимал у оператора десять минут, и половина звонивших клала трубку, услышав цифру.',
    },
    built: {
      az: 'Marşrut, çəki və yük növünə görə təxmini qiymət verən kalkulyator, avtoparkın səhifəsi və sənəd tələbləri bölməsi. Kalkulyatorun tarifləri şirkətin özünün redaktə edə biləcəyi cədvəldən oxunur.',
      en: 'A calculator that gives an indicative price from route, weight and cargo type, a fleet page, and a section on the paperwork a shipment needs. The calculator reads its rates from a table the company edits itself.',
      ru: 'Калькулятор, который выдаёт ориентировочную цену по маршруту, весу и типу груза, страница автопарка и раздел о необходимых документах. Тарифы калькулятор берёт из таблицы, которую компания правит сама.',
    },
    outcome: {
      az: 'Operatorlara gələn zənglərin sayı azalıb, amma sifarişə çevrilən zənglərin payı artıb — çünki zəng edənlər artıq qiyməti bilir.',
      en: 'Fewer calls reach the operators, but a larger share of them turn into bookings, because the people calling already know the price.',
      ru: 'Звонков стало меньше, но доля тех, что превращаются в заказ, выросла: звонящие уже знают цену.',
    },
    industry: 'logistics',
    stack: ['React', 'TypeScript', 'Vercel'],
    tags: ['calculator', 'lead-gen'],
    year: 2025,
    live_url: null,
    cover_image: '/assets/images/portfolio/kaspi-yuk-cover.jpg',
    gallery: [],
    published: true,
    sort_order: 30,
    created_at: now,
  },
  {
    id: 'demo-case-3',
    slug: 'cay-evi-sirvan',
    title: { az: 'Çay Evi Şirvan', en: 'Çay Evi Şirvan', ru: 'Чайхана «Ширван»' },
    client: 'Çay Evi Şirvan',
    summary: {
      az: 'Kağız menyunun yerinə telefondan açılan, həmişə güncəl menyu.',
      en: 'A menu that is always current, opened from the phone in the customer’s hand.',
      ru: 'Меню, которое всегда актуально и открывается с телефона гостя.',
    },
    problem: {
      az: 'Qiymətlər dəyişəndə menyu yenidən çap olunmalı idi və bu, ildə bir neçə dəfə baş verirdi. Köhnə menyular masalarda qalırdı, ofisiantlar isə hər dəfə fərqi izah etməli olurdu.',
      en: 'Every price change meant reprinting the menu, which happened several times a year. Old menus stayed on the tables, and waiters spent their shifts explaining the difference.',
      ru: 'Каждое изменение цен означало перепечатку меню, а это случалось несколько раз в год. Старые меню оставались на столах, и официанты весь день объясняли разницу.',
    },
    built: {
      az: 'QR koddan açılan menyu, şəkilli bölmələr və menyunu telefondan redaktə etmək üçün sadə panel. Sahibkar qiyməti dəyişəndə dəyişiklik masalardakı QR kodların hamısında dərhal görünür.',
      en: 'A QR-code menu with photographed sections and a small editor the owner uses from his phone. Change a price and every QR code on every table shows the new one immediately.',
      ru: 'Меню по QR-коду с фотографиями по разделам и простая панель, которой владелец пользуется с телефона. Меняешь цену — и на всех столах по QR открывается уже новая.',
    },
    outcome: {
      az: 'Çap xərci tamamilə aradan qalxıb. Menyuya əlavə olunan yeni mövsümi yeməklər elə həmin gün masalarda görünür.',
      en: 'Printing costs disappeared entirely. Seasonal dishes now appear on the tables the same day they are added.',
      ru: 'Расходы на печать исчезли совсем. Сезонные блюда появляются на столах в тот же день, когда их добавили.',
    },
    industry: 'hospitality',
    stack: ['React', 'Supabase'],
    tags: ['menu', 'qr', 'self-serve'],
    year: 2024,
    live_url: null,
    cover_image: '/assets/images/portfolio/cay-evi-cover.jpg',
    gallery: [],
    published: true,
    sort_order: 20,
    created_at: now,
  },
  {
    id: 'demo-case-4',
    slug: 'atlas-huquq',
    title: { az: 'Atlas Hüquq', en: 'Atlas Legal', ru: 'Atlas Legal' },
    client: 'Atlas Hüquq Bürosu',
    summary: {
      az: 'Hüquq bürosunun ilk saytı — sual verməyi asanlaşdıran quruluş.',
      en: 'A law office’s first site, built around making the first question easy to ask.',
      ru: 'Первый сайт юридического бюро, построенный вокруг того, чтобы первый вопрос было легко задать.',
    },
    problem: {
      az: 'Büro yeni müştəriləri yalnız tövsiyə ilə alırdı. İnternetdə axtaranlar onları tapmırdı, tapanlar isə nə ilə məşğul olduqlarını başa düşmürdü — çünki heç bir yerdə yazılmamışdı.',
      en: 'New clients arrived only by referral. People searching online did not find the firm, and the ones who did could not tell what it actually handled, because nothing said so.',
      ru: 'Новые клиенты приходили только по рекомендации. Те, кто искал в интернете, бюро не находили, а нашедшие не понимали, чем оно занимается, — нигде об этом не говорилось.',
    },
    built: {
      az: 'Praktika sahələri üzrə səhifələr, hər sahə üçün tipik sualların cavabı, vəkillərin qısa profilləri və ilk məsləhət üçün forma. Bütün mətn hüquqi dildən adi dilə çevrilib.',
      en: 'Pages per practice area, the questions each one usually starts with, short profiles of the lawyers, and a form for a first consultation. All the copy was rewritten out of legal register and into plain language.',
      ru: 'Страницы по направлениям практики, ответы на типичные вопросы по каждому, короткие профили юристов и форма записи на первую консультацию. Весь текст переписан с юридического языка на обычный.',
    },
    outcome: {
      az: 'Sayt işə düşəndən sonra büro ilk dəfə tövsiyə olmadan gələn müştəri qəbul etdi. Gələn müraciətlərin çoxu artıq hansı sahə ilə bağlı olduğunu bilir.',
      en: 'The firm took on its first non-referred client after launch. Most enquiries now arrive already knowing which practice area they belong to.',
      ru: 'После запуска бюро впервые приняло клиента, пришедшего не по рекомендации. Большинство обращений теперь сразу приходят по нужному направлению.',
    },
    industry: 'legal',
    stack: ['React', 'TypeScript'],
    tags: ['content', 'seo', 'multilingual'],
    year: 2024,
    live_url: null,
    cover_image: '/assets/images/portfolio/atlas-huquq-cover.jpg',
    gallery: [],
    published: true,
    sort_order: 10,
    created_at: now,
  },
];

export const demoListings: Listing[] = [
  {
    id: 'demo-listing-1',
    slug: 'vitrin',
    title: { az: 'Vitrin', en: 'Vitrin', ru: 'Vitrin' },
    tagline: {
      az: 'Bir səhifə, bir məqsəd: sizinlə əlaqə saxlasınlar.',
      en: 'One page, one job: get them to contact you.',
      ru: 'Одна страница, одна задача: чтобы вам написали.',
    },
    description: {
      az: 'Kiçik biznesin internetdə var olması üçün lazım olan minimum: nə etdiyiniz, kimlər üçün, qiymətlər, ünvan və xəritə, əlaqə forması. Telefonda kompüterdəki qədər səliqəli görünür və bir neçə saniyəyə açılır.',
      en: 'The minimum a small business needs to exist online: what you do, who for, prices, an address with a map, and a contact form. Looks the same on a phone as on a laptop and opens in a couple of seconds.',
      ru: 'Минимум, который нужен небольшому бизнесу, чтобы существовать в интернете: чем вы занимаетесь, для кого, цены, адрес с картой и форма связи. На телефоне выглядит так же аккуратно, как на ноутбуке, и открывается за пару секунд.',
    },
    best_for: {
      az: 'Bərbərxana, ustalar, kiçik studiya, fərdi mütəxəssis.',
      en: 'Barbers, trades, small studios, anyone working for themselves.',
      ru: 'Барбершопы, мастера, небольшие студии, частные специалисты.',
    },
    price_azn: 450,
    category: 'onepage',
    page_count: 1,
    pages: ['home', 'contact'],
    stack: ['React', 'TypeScript', 'Tailwind'],
    demo_url: null,
    cover_image: '/assets/images/marketplace/vitrin-cover.jpg',
    screenshots: [],
    license: 'single',
    status: 'published',
    sort_order: 40,
    created_at: now,
  },
  {
    id: 'demo-listing-2',
    slug: 'menyu',
    title: { az: 'Menyu', en: 'Menyu', ru: 'Menyu' },
    tagline: {
      az: 'Kafe və restoranlar üçün: menyu, foto, masa rezervasiyası.',
      en: 'For cafés and restaurants: menu, photos, table booking.',
      ru: 'Для кафе и ресторанов: меню, фотографии, бронь стола.',
    },
    description: {
      az: 'QR koddan açılan menyu, bölmələr üzrə şəkillər, iş saatları və rezervasiya forması. Menyunu özünüz redaktə edirsiniz — qiyməti dəyişmək üçün mənə yazmağa ehtiyac yoxdur. Masalara yapışdırmaq üçün QR kodlar hazır şəkildə verilir.',
      en: 'A QR-code menu, photographed by section, opening hours and a booking form. You edit the menu yourself — changing a price does not require messaging me. Table QR codes come ready to print.',
      ru: 'Меню по QR-коду, фотографии по разделам, часы работы и форма брони. Меню вы правите сами — чтобы поменять цену, писать мне не нужно. QR-коды для столов выдаются готовыми к печати.',
    },
    best_for: {
      az: 'Kafe, restoran, çayxana, şirniyyat evi.',
      en: 'Cafés, restaurants, tea houses, patisseries.',
      ru: 'Кафе, рестораны, чайханы, кондитерские.',
    },
    price_azn: 890,
    category: 'hospitality',
    page_count: 5,
    pages: ['home', 'services', 'gallery', 'booking', 'contact'],
    stack: ['React', 'Supabase', 'Tailwind'],
    demo_url: null,
    cover_image: '/assets/images/marketplace/menyu-cover.jpg',
    screenshots: [],
    license: 'single',
    status: 'published',
    sort_order: 30,
    created_at: now,
  },
  {
    id: 'demo-listing-3',
    slug: 'kataloq',
    title: { az: 'Kataloq', en: 'Kataloq', ru: 'Kataloq' },
    tagline: {
      az: 'Məhsul kataloqu — ödəniş sistemi qurmadan satışa başlayın.',
      en: 'A product catalogue that starts selling before you set up payments.',
      ru: 'Каталог товаров: продажи начинаются до подключения оплаты.',
    },
    description: {
      az: 'Kateqoriyalar, məhsul səhifələri, axtarış və filtrlər. Sifariş WhatsApp-a və ya e-poçta gedir, ona görə bank terminalı gözləmədən satışa başlaya bilirsiniz. Sonradan onlayn ödəniş əlavə etmək istəsəniz, quruluş buna hazırdır.',
      en: 'Categories, product pages, search and filters. Orders go to WhatsApp or email, so you can start selling without waiting on a payment terminal. If you add online payments later, the structure is already built for it.',
      ru: 'Категории, страницы товаров, поиск и фильтры. Заказы уходят в WhatsApp или на почту, так что продавать можно, не дожидаясь эквайринга. Если позже захотите онлайн-оплату — структура к этому готова.',
    },
    best_for: {
      az: 'Mebel, geyim, avadanlıq, topdan satış.',
      en: 'Furniture, clothing, equipment, wholesale.',
      ru: 'Мебель, одежда, оборудование, оптовая торговля.',
    },
    price_azn: 1250,
    category: 'catalog',
    page_count: 8,
    pages: ['home', 'catalog', 'about', 'contact'],
    stack: ['React', 'Supabase', 'Tailwind'],
    demo_url: null,
    cover_image: '/assets/images/marketplace/kataloq-cover.jpg',
    screenshots: [],
    license: 'single',
    status: 'published',
    sort_order: 20,
    created_at: now,
  },
  {
    id: 'demo-listing-4',
    slug: 'klinika',
    title: { az: 'Klinika', en: 'Klinika', ru: 'Klinika' },
    tagline: {
      az: 'Həkimlər, xidmətlər, qiymətlər və onlayn qeydiyyat.',
      en: 'Doctors, services, prices and appointments that book themselves.',
      ru: 'Врачи, услуги, цены и запись, которая работает сама.',
    },
    description: {
      az: 'Həkim profilləri, xidmət və qiymət cədvəli, iş saatlarına bağlı qeydiyyat forması və üç dil. Qeydiyyat sizin telefonunuza bildiriş kimi gəlir; ayrıca panel öyrənmək lazım deyil.',
      en: 'Doctor profiles, a service and price table, a booking form tied to opening hours, and three languages. Appointments arrive as a notification on your phone — there is no separate dashboard to learn.',
      ru: 'Профили врачей, таблица услуг и цен, форма записи, привязанная к часам приёма, и три языка. Запись приходит уведомлением на телефон — отдельную панель осваивать не нужно.',
    },
    best_for: {
      az: 'Diş klinikası, kosmetologiya, tibbi mərkəz, laboratoriya.',
      en: 'Dental practices, cosmetology, medical centres, laboratories.',
      ru: 'Стоматологии, косметология, медцентры, лаборатории.',
    },
    price_azn: 1600,
    category: 'health',
    page_count: 9,
    pages: ['home', 'services', 'about', 'booking', 'contact'],
    stack: ['React', 'Supabase', 'Tailwind'],
    demo_url: null,
    cover_image: '/assets/images/marketplace/klinika-cover.jpg',
    screenshots: [],
    license: 'single',
    status: 'published',
    sort_order: 10,
    created_at: now,
  },
];
